version: '2'

services:
    web:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7-fpm
        volumes:
            - ./code:/code

# Use root/example as user/password credentials
    db:
        image: mariadb
        volumes:
            - ./data/:/var/lib/mysql/
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        volumes:
            - /sessions/
        environment:
            PMA_HOST: db
        restart: always
        ports:
            - 8081:80
